### ISSUE TITLE
How do you use this container?

### ISSUE THREAD

**Issue by richb-hanover** [cmu-sei/certccsilklive#1]
Thanks for pulling together the SiLK container. But it would be helpful to know how to use it in a broader context:

- Can I have my netflow exporters send live data to the container?
- How can I retrieve data from the container?

Thanks!

**Comment by richb-hanover** [comment]
**Update:** This dockerfile was useful for getting me started. I have posted information about a couple Netflow collectors (some using SiLK) at my blog: http://richb-hanover.com/netflow-collectors-for-home-networks/

**Comment by maheckathorn** [comment]
Hey,

My apologies for this taking so long.  The intention of this specific container is really for providing training courses with [ISLET](https://github.com/jonschipp/ISLET), it's not really meant to be used outside of that use case.  If you are still interested, we just published a set of containers that are more in line with what you are looking for:

https://github.com/cmu-sei/docker-super_mediator
https://github.com/cmu-sei/docker-silk_analysis
https://github.com/cmu-sei/docker-silk_packing
https://github.com/cmu-sei/docker-yaf
https://github.com/cmu-sei/docker-fixbuf

Again, apologies for taking so long to get back to you.

**Comment by richb-hanover** [comment]
@maheckathorn Thanks for following up. 

It's strange: after sitting essentially idle for about 7 years, my blog post [Netflow Collectors for Home Networks](https://randomneuronsfiring.com/netflow-collectors-for-home-networks/)  seems to have stirred up _two_ various comments/inquiries from people in the last week.

Is Netflow having a resurgence of popularity?
